#!/bin/sh
acr -p
cd lib && acr -p

exit 0
# amr: autogenerated autogen.sh
echo "Autogenerating configure.amr..."
amr -a > configure.amr
DIRS=`amr -d`
echo "Source directories: ${DIRS}"
for A in ${DIRS}; do
        echo " - ${A}"
        (cd ${A} && amr -a > configure.amr)
done
echo "Generating configure.acr..."
amr -c > configure.acr
echo "Generating final configure script..."
acr -p
