include ../../config.mk
LIBDIR=@LIBDIR@
DATADIR=@DATADIR@
INSTALL_LIB=@INSTALL_LIB@
INSTALL_DATA=@INSTALL_DATA@
VPATH=@VPATH@
HELPERS=-L../../src -lsal
CFLAGS+=-I ../../src
LDFLAGS+=-shared
OBJ=libsalregex.o

all: ${OBJ}
	${CC} ${LDFLAGS} ${HELPERS} ${OBJ} -o libsalregex.$(EXT_SO)

install:
	${INSTALL_LIB} libsalregex.$(EXT_SO) ${LIBDIR}
	${INSTALL_DATA} regex.cpp ${DATADIR}/sal/include

clean:
	-rm -f *.$(EXT_SO) *.o

.PHONY: all install clean
